"""
Logging Utility Module
Author: BLESSING OMOREGIE
GitHub: Nixiestone
Repository: nyx_trial

DO NOT EDIT THIS FILE
Provides centralized logging for the entire trading bot.
"""

import logging
import sys
from pathlib import Path
from logging.handlers import RotatingFileHandler
from datetime import datetime
from typing import Optional
import colorlog


class TradingBotLogger:
    """
    Custom logger for the trading bot with file and console output.
    Includes color-coded console output and rotating file handlers.
    """
    
    def __init__(
        self,
        name: str,
        log_level: str = "INFO",
        log_file: Optional[str] = None,
        max_bytes: int = 10485760,
        backup_count: int = 5
    ):
        """
        Initialize the logger.
        
        Args:
            name: Logger name (usually module name)
            log_level: Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
            log_file: Path to log file (optional)
            max_bytes: Maximum size of log file before rotation
            backup_count: Number of backup files to keep
        """
        self.logger = logging.getLogger(name)
        self.logger.setLevel(getattr(logging, log_level.upper()))
        self.logger.propagate = False
        
        # Remove existing handlers
        if self.logger.handlers:
            self.logger.handlers.clear()
        
        # Create formatters
        self._add_console_handler()
        
        if log_file:
            self._add_file_handler(log_file, max_bytes, backup_count)
    
    def _add_console_handler(self):
        """Add color-coded console handler."""
        console_handler = colorlog.StreamHandler(sys.stdout)
        console_formatter = colorlog.ColoredFormatter(
            '%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S',
            log_colors={
                'DEBUG': 'cyan',
                'INFO': 'green',
                'WARNING': 'yellow',
                'ERROR': 'red',
                'CRITICAL': 'red,bg_white',
            }
        )
        console_handler.setFormatter(console_formatter)
        self.logger.addHandler(console_handler)
    
    def _add_file_handler(self, log_file: str, max_bytes: int, backup_count: int):
        """Add rotating file handler."""
        log_path = Path(log_file)
        log_path.parent.mkdir(parents=True, exist_ok=True)
        
        file_handler = RotatingFileHandler(
            log_file,
            maxBytes=max_bytes,
            backupCount=backup_count
        )
        file_formatter = logging.Formatter(
            '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        file_handler.setFormatter(file_formatter)
        self.logger.addHandler(file_handler)
    
    def debug(self, message: str, **kwargs):
        """Log debug message."""
        self.logger.debug(message, **kwargs)
    
    def info(self, message: str, **kwargs):
        """Log info message."""
        self.logger.info(message, **kwargs)
    
    def warning(self, message: str, **kwargs):
        """Log warning message."""
        self.logger.warning(message, **kwargs)
    
    def error(self, message: str, **kwargs):
        """Log error message."""
        self.logger.error(message, **kwargs)
    
    def critical(self, message: str, **kwargs):
        """Log critical message."""
        self.logger.critical(message, **kwargs)
    
    def exception(self, message: str, **kwargs):
        """Log exception with traceback."""
        self.logger.exception(message, **kwargs)
    
    def trade_signal(self, signal_type: str, symbol: str, details: dict):
        """
        Log trading signal with structured format.
        
        Args:
            signal_type: BUY, SELL, or CLOSE
            symbol: Trading symbol
            details: Signal details dictionary
        """
        self.logger.info(
            f"SIGNAL [{signal_type}] {symbol} | "
            f"Entry: {details.get('entry', 'N/A')} | "
            f"SL: {details.get('stop_loss', 'N/A')} | "
            f"TP1: {details.get('tp1', 'N/A')} | "
            f"TP2: {details.get('tp2', 'N/A')} | "
            f"Score: {details.get('score', 'N/A')}"
        )
    
    def trade_execution(self, action: str, symbol: str, details: dict):
        """
        Log trade execution.
        
        Args:
            action: OPENED, CLOSED, PARTIAL_CLOSE
            symbol: Trading symbol
            details: Execution details
        """
        self.logger.info(
            f"EXECUTION [{action}] {symbol} | "
            f"Price: {details.get('price', 'N/A')} | "
            f"Quantity: {details.get('quantity', 'N/A')} | "
            f"PnL: {details.get('pnl', 'N/A')}"
        )
    
    def model_prediction(self, symbol: str, predictions: dict):
        """
        Log ML model predictions.
        
        Args:
            symbol: Trading symbol
            predictions: Dictionary of model predictions
        """
        self.logger.debug(
            f"MODEL PREDICTION {symbol} | "
            f"Model1: {predictions.get('model1', 'N/A')} | "
            f"Model2: {predictions.get('model2', 'N/A')} | "
            f"Model3: {predictions.get('model3', 'N/A')} | "
            f"Ensemble: {predictions.get('ensemble', 'N/A')}"
        )
    
    def sentiment_analysis(self, symbol: str, sentiment: dict):
        """
        Log sentiment analysis results.
        
        Args:
            symbol: Trading symbol
            sentiment: Sentiment analysis results
        """
        self.logger.debug(
            f"SENTIMENT {symbol} | "
            f"Score: {sentiment.get('score', 'N/A')} | "
            f"Label: {sentiment.get('label', 'N/A')} | "
            f"Confidence: {sentiment.get('confidence', 'N/A')}"
        )
    
    def smc_analysis(self, symbol: str, timeframe: str, analysis: dict):
        """
        Log SMC (Smart Money Concepts) analysis.
        
        Args:
            symbol: Trading symbol
            timeframe: Analysis timeframe
            analysis: SMC analysis results
        """
        self.logger.debug(
            f"SMC [{timeframe}] {symbol} | "
            f"Trend: {analysis.get('trend', 'N/A')} | "
            f"Structure: {analysis.get('structure', 'N/A')} | "
            f"POI: {analysis.get('poi_type', 'N/A')} | "
            f"Valid: {analysis.get('valid', 'N/A')}"
        )
    
    def performance_metric(self, metric_name: str, value: float, symbol: Optional[str] = None):
        """
        Log performance metrics.
        
        Args:
            metric_name: Name of the metric
            value: Metric value
            symbol: Trading symbol (optional)
        """
        symbol_str = f"{symbol} " if symbol else ""
        self.logger.info(f"METRIC {symbol_str}| {metric_name}: {value}")
    
    def risk_warning(self, message: str, details: dict):
        """
        Log risk management warnings.
        
        Args:
            message: Warning message
            details: Additional details
        """
        self.logger.warning(
            f"RISK WARNING: {message} | Details: {details}"
        )


def get_logger(
    name: str,
    log_level: str = "INFO",
    log_file: Optional[str] = None
) -> TradingBotLogger:
    """
    Factory function to create a logger instance.
    
    Args:
        name: Logger name
        log_level: Logging level
        log_file: Log file path
        
    Returns:
        TradingBotLogger instance
    """
    return TradingBotLogger(name, log_level, log_file)


# Create default logger for the application
def setup_default_logger(config):
    """
    Set up the default logger using configuration settings.
    
    Args:
        config: Settings object from config/settings.py
        
    Returns:
        TradingBotLogger instance
    """
    return get_logger(
        name="TradingBot",
        log_level=config.LOG_LEVEL,
        log_file=config.LOG_FILE_PATH
    )


if __name__ == "__main__":
    # Test logger
    test_logger = get_logger("TestLogger", "DEBUG", "logs/test.log")
    
    test_logger.info("Logger initialized successfully")
    test_logger.debug("This is a debug message")
    test_logger.warning("This is a warning")
    test_logger.error("This is an error")
    
    test_logger.trade_signal(
        "BUY",
        "BTC/USDT",
        {
            "entry": 50000.0,
            "stop_loss": 49500.0,
            "tp1": 50750.0,
            "tp2": 51500.0,
            "score": 0.85
        }
    )
    
    print("Logger test completed. Check logs/test.log")