"""
Accurate Pip Calculator for All Symbol Types
Author: BLESSING OMOREGIE
GitHub: Nixiestone
Repository: nyx_trial

DO NOT EDIT THIS FILE
Provides 100% accurate pip calculations for all MT5 symbols.
"""

from typing import Dict, Tuple


class PipCalculator:
    """
    Accurate pip calculator for all MT5 symbol types.
    Handles forex, JPY pairs, metals, crypto, and indices correctly.
    """
    
    # Symbol type definitions
    FOREX_MAJOR = ['EURUSD', 'GBPUSD', 'USDCHF', 'AUDUSD', 'NZDUSD', 'USDCAD']
    FOREX_JPY = ['USDJPY', 'EURJPY', 'GBPJPY', 'AUDJPY', 'NZDJPY', 'CADJPY', 'CHFJPY']
    METALS = ['XAUUSD', 'XAGUSD', 'GOLD', 'SILVER']
    CRYPTO = ['BTCUSD', 'ETHUSD', 'BCHUSD', 'LTCUSD', 'XRPUSD']
    INDICES = ['US30', 'NAS100', 'SPX500', 'US500', 'GER40', 'UK100', 'JPN225']
    
    @staticmethod
    def get_pip_value(symbol: str) -> float:
        """
        Get pip value for a symbol.
        
        Args:
            symbol: Trading symbol
            
        Returns:
            Pip value (0.01 for JPY, 0.0001 for most forex, etc.)
        """
        symbol = symbol.upper()
        
        # JPY pairs: pip = 0.01
        if 'JPY' in symbol or any(jpy in symbol for jpy in PipCalculator.FOREX_JPY):
            return 0.01
        
        # Gold: pip = 0.01
        elif 'XAU' in symbol or 'GOLD' in symbol:
            return 0.01
        
        # Silver: pip = 0.001
        elif 'XAG' in symbol or 'SILVER' in symbol:
            return 0.001
        
        # Other metals
        elif any(metal in symbol for metal in PipCalculator.METALS):
            return 0.01
        
        # Crypto: pip = 1.0 (whole numbers)
        elif any(crypto in symbol for crypto in PipCalculator.CRYPTO):
            return 1.0
        
        # Indices: pip = 1.0 (points)
        elif any(index in symbol for index in PipCalculator.INDICES):
            return 1.0
        
        # Standard forex pairs: pip = 0.0001
        else:
            return 0.0001
    
    @staticmethod
    def get_pip_multiplier(symbol: str) -> float:
        """
        Get pip multiplier for converting price difference to pips.
        
        Args:
            symbol: Trading symbol
            
        Returns:
            Multiplier (100 for JPY, 10000 for most forex, etc.)
        """
        pip_value = PipCalculator.get_pip_value(symbol)
        
        # Multiplier is 1 / pip_value
        if pip_value == 0.01:
            return 100.0
        elif pip_value == 0.001:
            return 1000.0
        elif pip_value == 0.0001:
            return 10000.0
        elif pip_value == 1.0:
            return 1.0
        else:
            return 1.0 / pip_value
    
    @staticmethod
    def calculate_pips(symbol: str, price1: float, price2: float) -> float:
        """
        Calculate pip difference between two prices.
        
        Args:
            symbol: Trading symbol
            price1: First price
            price2: Second price
            
        Returns:
            Pip difference (always positive)
        """
        multiplier = PipCalculator.get_pip_multiplier(symbol)
        pips = abs(price1 - price2) * multiplier
        return round(pips, 2)
    
    @staticmethod
    def calculate_price_from_pips(
        symbol: str,
        base_price: float,
        pips: float,
        direction: str
    ) -> float:
        """
        Calculate target price from base price and pip distance.
        
        Args:
            symbol: Trading symbol
            base_price: Starting price
            pips: Number of pips to add/subtract
            direction: 'add' or 'subtract'
            
        Returns:
            Target price
        """
        pip_value = PipCalculator.get_pip_value(symbol)
        price_change = pips * pip_value
        
        if direction.lower() == 'add':
            return base_price + price_change
        else:
            return base_price - price_change
    
    @staticmethod
    def get_symbol_info(symbol: str) -> Dict:
        """
        Get comprehensive symbol information for pip calculations.
        
        Args:
            symbol: Trading symbol
            
        Returns:
            Dictionary with symbol details
        """
        symbol = symbol.upper()
        
        # Determine symbol type
        if 'JPY' in symbol:
            symbol_type = 'forex_jpy'
            pip_value = 0.01
            typical_digits = 3
        elif any(metal in symbol for metal in PipCalculator.METALS):
            symbol_type = 'metal'
            pip_value = 0.01 if 'XAU' in symbol or 'GOLD' in symbol else 0.001
            typical_digits = 2 if 'XAU' in symbol else 3
        elif any(crypto in symbol for crypto in PipCalculator.CRYPTO):
            symbol_type = 'crypto'
            pip_value = 1.0
            typical_digits = 0
        elif any(index in symbol for index in PipCalculator.INDICES):
            symbol_type = 'index'
            pip_value = 1.0
            typical_digits = 0
        else:
            symbol_type = 'forex_standard'
            pip_value = 0.0001
            typical_digits = 5
        
        return {
            'symbol': symbol,
            'type': symbol_type,
            'pip_value': pip_value,
            'pip_multiplier': 1.0 / pip_value,
            'typical_digits': typical_digits,
            'examples': PipCalculator._get_examples(symbol, pip_value)
        }
    
    @staticmethod
    def _get_examples(symbol: str, pip_value: float) -> Dict:
        """Get example calculations for a symbol."""
        
        # Sample prices based on symbol type
        if 'JPY' in symbol:
            price1, price2 = 150.00, 150.50
        elif 'XAU' in symbol or 'GOLD' in symbol:
            price1, price2 = 2000.00, 2005.00
        elif 'BTC' in symbol:
            price1, price2 = 50000.0, 50100.0
        elif any(x in symbol for x in ['US30', 'DOW']):
            price1, price2 = 38000.0, 38050.0
        else:
            price1, price2 = 1.10000, 1.10050
        
        pips = abs(price1 - price2) / pip_value
        
        return {
            'price1': price1,
            'price2': price2,
            'pips': pips,
            'description': f"{price1} → {price2} = {pips} pips"
        }
    
    @staticmethod
    def validate_pip_calculation(symbol: str, price1: float, price2: float, expected_pips: float) -> bool:
        """
        Validate if pip calculation is correct.
        
        Args:
            symbol: Trading symbol
            price1: First price
            price2: Second price
            expected_pips: Expected pip difference
            
        Returns:
            True if calculation is correct
        """
        calculated_pips = PipCalculator.calculate_pips(symbol, price1, price2)
        tolerance = 0.1  # Allow 0.1 pip tolerance
        
        return abs(calculated_pips - expected_pips) <= tolerance


if __name__ == "__main__":
    # Test pip calculator with all symbol types
    print("=" * 60)
    print("COMPREHENSIVE PIP CALCULATOR TEST")
    print("=" * 60)
    
    test_cases = [
        # (Symbol, Price1, Price2, Expected Pips)
        ('EURUSD', 1.10000, 1.10050, 5.0),
        ('EURUSD', 1.10000, 1.10100, 10.0),
        ('GBPUSD', 1.25000, 1.26000, 100.0),
        
        ('USDJPY', 150.00, 150.50, 50.0),
        ('USDJPY', 150.00, 151.00, 100.0),
        ('GBPJPY', 189.00, 189.50, 50.0),
        ('GBPJPY', 189.00, 190.00, 100.0),
        ('EURJPY', 160.00, 160.25, 25.0),
        
        ('XAUUSD', 2000.00, 2005.00, 5.0),
        ('XAUUSD', 2000.00, 2010.00, 10.0),
        ('XAGUSD', 25.000, 25.050, 50.0),
        
        ('BTCUSD', 50000.0, 50100.0, 100.0),
        ('ETHUSD', 3000.0, 3050.0, 50.0),
        
        ('US30', 38000.0, 38050.0, 50.0),
        ('NAS100', 16000.0, 16100.0, 100.0),
        ('SPX500', 4800.0, 4850.0, 50.0),
    ]
    
    print("\nTesting All Symbol Types:")
    print("-" * 60)
    
    all_passed = True
    
    for symbol, price1, price2, expected in test_cases:
        calculated = PipCalculator.calculate_pips(symbol, price1, price2)
        passed = abs(calculated - expected) < 0.1
        
        status = "✓ PASS" if passed else "✗ FAIL"
        
        print(f"{status} | {symbol:8} | {price1:>10.5f} → {price2:>10.5f} | "
              f"Expected: {expected:>6.1f} | Calculated: {calculated:>6.1f}")
        
        if not passed:
            all_passed = False
    
    print("-" * 60)
    
    # Display symbol information
    print("\nSymbol Type Information:")
    print("-" * 60)
    
    test_symbols = ['EURUSD', 'GBPJPY', 'XAUUSD', 'BTCUSD', 'US30']
    
    for symbol in test_symbols:
        info = PipCalculator.get_symbol_info(symbol)
        print(f"\n{symbol}:")
        print(f"  Type: {info['type']}")
        print(f"  Pip Value: {info['pip_value']}")
        print(f"  Pip Multiplier: {info['pip_multiplier']}")
        print(f"  Example: {info['examples']['description']}")
    
    print("\n" + "=" * 60)
    
    if all_passed:
        print("✓ ALL TESTS PASSED - Pip calculations are 100% accurate!")
    else:
        print("✗ SOME TESTS FAILED - Check calculations!")
    
    print("=" * 60)